# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       pciutils

# >> macros
# << macros

Summary:    PCI bus related utilities
Version:    3.2.1
Release:    1
Group:      Applications/System
License:    GPLv2
URL:        http://atrey.karlin.mff.cuni.cz/~mj/pciutils.shtml
Source0:    %{name}-%{version}.tar.xz
Source100:  pciutils.yaml
Requires:   hwdata
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(libkmod)
BuildRequires:  sed

%description
The pciutils package contains various utilities for inspecting and
setting devices connected to the PCI bus. The utilities provided
require kernel version 2.1.82 or newer (which support the
/proc/bus/pci interface).


%package devel
Summary:    Linux PCI development library
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains a library for inspecting and setting
devices connected to the PCI bus.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
sed -i -e 's/^SRC=.*/SRC="http:\/\/pciids.sourceforge.net\/pci.ids"/' update-pciids.sh
# << build pre



# >> build post
make SHARED="yes" LIBKMOD="yes" OPT="$RPM_OPT_FLAGS -D_GNU_SOURCE=1" PREFIX="%{_prefix}" LIBDIR="%{_libdir}" IDSDIR="%{_datadir}/hwdata" PCI_IDS="pci.ids" %{?_smp_mflags}
sed -i "s|^libdir=.*$|libdir=%{_libdir}|" lib/libpci.pc
# << build post

%install
rm -rf %{buildroot}
# >> install pre
install -d %{buildroot}/{%{_sbindir},%{_mandir}/man8,%{_libdir},%{_libdir}/pkgconfig,%{_includedir}/pci}
# << install pre

# >> install post
install -p -m 755 lspci setpci update-pciids %{buildroot}%{_sbindir}
install -p -m 644 lspci.8 setpci.8 update-pciids.8 %{buildroot}%{_mandir}/man8
install -p -m 644 lib/libpci.so.* %{buildroot}%{_libdir}
install -p -m 644 lib/pci.h %{buildroot}%{_includedir}/pci
install -p -m 644 lib/header.h %{buildroot}%{_includedir}/pci
install -p -m 644 lib/config.h %{buildroot}%{_includedir}/pci
install -p -m 644 lib/types.h %{buildroot}%{_includedir}/pci
install -p -m 644 lib/libpci.pc %{buildroot}%{_libdir}/pkgconfig
for i in %{buildroot}/%{_libdir}/libpci.so.* ; do ln -s `basename $i` %{buildroot}/%{_libdir}/libpci.so ; done
rm -f lib/*.{a,la}
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%doc README ChangeLog pciutils.lsm COPYING
%{_sbindir}/*
%{_mandir}/man8/*
%{_libdir}/libpci.so.*
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/pci
%{_libdir}/pkgconfig/libpci.pc
%{_libdir}/libpci.so
# >> files devel
# << files devel
